name: Azure Couture
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7541
title: 'Unforgettable & Stylish Stationery'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfd6ce'
    - '#03091f'
    - '#064e67'
    - '#65a7b5'
    - '#007e94'
  brandStrength: 0.3125
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
